services:
  postgres:
    image: postgres
    restart: always
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DATABASE_POSTGRES_PORT}:5432
volumes:
  postgres: